name: Clippy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'LICENSE'
    - 'README'
    - '**.md'
    - 'templates/*'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'LICENSE'
    - 'README'
    - '**.md'
    - 'templates/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add Clippy
        run: rustup component add clippy

      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
