name: Clippy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'LICENSE'
    - 'README'
    - '**.md'
    - 'templates/*'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'LICENSE'
    - 'README'
    - '**.md'
    - 'templates/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get clippy toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
